// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgghfLfk-GL1mLaDAvM7PVfGI8q8vT6U',
    appId: '1:59181756680:ios:848a969624c60761f3fcbd',
    messagingSenderId: '59181756680',
    projectId: 'fir-demo-e6b12',
    databaseURL: 'https://fir-demo-e6b12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-e6b12.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAtvixephRkjFGAbX_c_nOoSNiE77436M',
    appId: '1:59181756680:web:bae93b743a4c8bfff3fcbd',
    messagingSenderId: '59181756680',
    projectId: 'fir-demo-e6b12',
    authDomain: 'fir-demo-e6b12.firebaseapp.com',
    databaseURL: 'https://fir-demo-e6b12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-e6b12.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAtvixephRkjFGAbX_c_nOoSNiE77436M',
    appId: '1:59181756680:web:bae93b743a4c8bfff3fcbd',
    messagingSenderId: '59181756680',
    projectId: 'fir-demo-e6b12',
    authDomain: 'fir-demo-e6b12.firebaseapp.com',
    databaseURL: 'https://fir-demo-e6b12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-e6b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgghfLfk-GL1mLaDAvM7PVfGI8q8vT6U',
    appId: '1:59181756680:ios:848a969624c60761f3fcbd',
    messagingSenderId: '59181756680',
    projectId: 'fir-demo-e6b12',
    databaseURL: 'https://fir-demo-e6b12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-e6b12.appspot.com',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfAbqTxM8ckCmL9ESxXAwMTg6uSGxhQI',
    appId: '1:59181756680:android:6b200dc75aa1da13f3fcbd',
    messagingSenderId: '59181756680',
    projectId: 'fir-demo-e6b12',
    databaseURL: 'https://fir-demo-e6b12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-e6b12.appspot.com',
  );

}